export const skills = [
    {title: 'Typescript',icon: '/icons/typescript.png'},
    {title: 'Javascript',icon: '/icons/javascript.png'},
    {title: 'Docker',icon: '/icons/docker.png'},    
    {title: 'NextJs',icon: '/icons/nextjs.png'},
    {title: 'React',icon: '/icons/react.png'},
    {title: 'Figma',icon: '/icons/figma.png'},
    {title: 'AWS',icon: '/icons/aws.png'},
    {title: 'HTML 5',icon: '/icons/html.png'},
    {title: 'Postgresql',icon: '/icons/postgresql.png'},
    {title: 'Neon DB',icon: '/icons/neon.png'},
    {title: 'Prisma',icon: '/icons/prisma.png'},
    {title: 'CSS 3',icon: '/icons/css.png'},
    {title: 'Node',icon: '/icons/nodejs.png'},
    {title: 'Tailwind',icon: '/icons/tailwind.png'},
    {title: 'Vscode',icon: '/icons/vscode.png'},    
    {title: 'Express',icon: '/icons/express.png'},    
    {title: 'Mongo DB',icon: '/icons/mongodb.png'},     
    {title: 'Postman',icon: '/icons/postman.png'},    
    {title: 'Rest API',icon: '/icons/restapi.png'},    
    {title: 'Redux',icon: '/icons/redux.png'},    
]